x-net-config:
  &net-config
  network_mode: host
  ipc: host
  env_file: net.env

services:

  foxglove:
    image: husarion/foxglove:humble-nightly
    volumes:
      - ./RosbotTeleop.json:/src/RosbotTeleop.json
      - ./caddy_entrypoint.sh:/caddy_entrypoint.sh
    ports:
      - 8081:8080
    # entrypoint: ["/bin/sh","/caddy_entrypoint.sh"]

  foxglove-assets:
    build:
      dockerfile: Dockerfile.assets
    network_mode: host
    environment:
      # - ROSBOT_ADDR=10.5.10.206
      - ROSBOT_ADDR=fc94:3434:dbb4:20f8:d7ef:89b7:7c8c:b5e7
      - PORT=8083
    # ports:
    #   - 8081:8080

  rosbridge:
    image: husarion/rosbridge:humble-nightly
    ports:
      - 9090:9090
    command: ros2 launch rosbridge_server rosbridge_websocket_launch.xml  

  rosbot:
    image: husarion/rosbot:humble
    command: ros2 launch rosbot_bringup bringup.launch.py

  microros:
    image: husarion/micro-ros-agent:humble
    devices:
      - ${SERIAL_PORT:?err}
    command: ros2 run micro_ros_agent micro_ros_agent serial -D $SERIAL_PORT serial -b 576000 # -v6

  rplidar:
    image: husarion/rplidar:humble
    devices:
      - ${LIDAR_SERIAL:?err}:/dev/ttyUSB0
    command: ros2 launch sllidar_ros2 sllidar_launch.py serial_baudrate:=${LIDAR_BAUDRATE:-115200}

  slam:
    image: husarion/navigation2:humble
    depends_on:
      rplidar: { condition: service_healthy }
    volumes:
      - ./params/${SLAM_MODE:-slam}.yaml:/params.yaml
      - ./maps:/maps
    environment:
      - SLAM_MODE=${SLAM_MODE:-slam}
    command: >
      ros2 launch nav2_bringup ${SLAM_MODE:-slam}_launch.py
        params_file:=/params.yaml
        map:=/maps/map.yaml
        use_sim_time:=False

  navigation:
    image: husarion/navigation2:humble
    depends_on:
      slam: { condition: service_healthy }
    volumes:
      - ./params/nav2.yaml:/params.yaml
    environment:
      - SLAM_MODE=${SLAM_MODE:-slam}
    command: >
      bash -c "
        if [[ \"\$SLAM_MODE\" == \"localization\" ]]; then
          ros2 launch nav2_bringup navigation_launch.py
          params_file:=/params.yaml
          use_sim_time:=False;
        fi
      "
